### ISSUE TITLE
Temperature does not work

### ISSUE THREAD

**Issue by neurogen-dev** [SirFreddie/fred_metabolism#1]
The temperature scale does not work, it says "Loading" for all players.

**Comment by SirFreddie** [comment]
> The temperature scale does not work, it says "Loading" for all players.

Did you restarted the resource? Or it says that after you started the server? Also, is it everytime or just sometimes that temperature isn't working?

I think i have an idea on what it could be, i'll probably push an update later!

**Comment by neurogen-dev** [comment]
I added HUD and metabolism, turned off the standard metabolic module and restarted the server. After the restart, all players do not display the temperature. In addition, it seemed to me that other indicators do not work either. The consumption of food and water does not change the state of the indicators.

**Comment by SirFreddie** [comment]
Alright, also check on your console (F8) if you are getting an error something like: no export getHunger.

Also, make sure you aren't registering the items somewhere else (for eg:Malik_items) this script register items automatically. If you register this items somewhere else with the same name, it may cause conflict.
